# Generated by Django 5.2.5 on 2025-10-08 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fields', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_center', to='design.researchowner')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.researcher')),
            ],
        ),
        migrations.CreateModel(
            name='ReformulatedResearchQuestionIteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled_fields', models.JSONField(default=dict)),
                ('reformulated_research_question', models.TextField()),
                ('status', models.CharField(choices=[('incomplete_draft', 'Incomplete Draft'), ('to_review', 'To Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, max_length=20)),
                ('iteration_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='design.framework')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iterations_as_researcher', to='design.researcher')),
                ('research_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refinements', to='design.researchquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchQuestionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.reformulatedresearchquestioniteration')),
                ('research_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='design.researchquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approval_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='design.approvalcenter')),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_items', to='design.reformulatedresearchquestioniteration')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.researcher')),
            ],
            options={
                'indexes': [models.Index(fields=['approval_center', 'submitted_at'], name='design_appr_approva_186d8d_idx'), models.Index(fields=['iteration'], name='design_appr_iterati_f0b262_idx')],
                'unique_together': {('approval_center', 'iteration')},
            },
        ),
        migrations.AddIndex(
            model_name='approvalcenter',
            index=models.Index(fields=['owner'], name='design_appr_owner_i_da5e58_idx'),
        ),
        migrations.AddIndex(
            model_name='researchquestionhistory',
            index=models.Index(fields=['research_question', 'recorded_at'], name='design_rese_researc_a6ca29_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='researchquestionhistory',
            unique_together={('research_question', 'iteration')},
        ),
    ]
