# Generated by Django 5.2.5 on 2025-10-14 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('justification', models.TextField()),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('validator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations_performed', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_history', to='design.researchquestionversion')),
            ],
            options={
                'ordering': ['-validated_at'],
            },
        ),
    ]
