# Generated by Django 5.2.5 on 2025-10-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reformulatedresearchquestioniteration',
            name='reformulated_research_question',
            field=models.TextField(blank=True),
        ),
    ]
